FROM smartgic/mycroft-base:arm32v7-dev

MAINTAINER Gaëtan Trellu <gaetan.trellu@smartgic.io>

LABEL vendor=Smartgic.io \
      io.smartgic.image-name="mycroft-enclosure" \
      io.smartgic.is-beta="no" \
      io.smartgic.is-production="no" \
      io.smartgic.version="dev" \
      io.smartgic.release-date="2021-01-01"

WORKDIR /home/mycroft/core

USER mycroft

ENTRYPOINT ["python", "-m", "mycroft.client.enclosure"]
