FROM smartgic/mycroft-base:amd64-dev

LABEL vendor=Smartgic.io \
      io.smartgic.maintainer="Gaëtan Trellu <gaetan.trellu@smartgic.io>" \
      io.smartgic.image-name="mycroft-enclosure" \
      io.smartgic.is-beta="no" \
      io.smartgic.is-production="no" \
      io.smartgic.version="dev" \
      io.smartgic.release-date="2021-01-01"

WORKDIR /home/mycroft/core

USER mycroft

ENTRYPOINT ["python", "-m", "mycroft.client.enclosure"]
