---
version: "3.8"

volumes:
  mycroft_skills:
    name: mycroft_skills
    driver: local
  mycroft_skills_repo:
    name: mycroft_skills_repo
    driver: local
  mycroft_skills_venv:
    name: mycroft_venv
    driver: local

services:
  mycroft_bus:
    container_name: mycroft_bus
    hostname: mycroft_bus
    restart: unless-stopped
    image: smartgic/mycroft-bus:${VERSION}
    network_mode: host
    ipc: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft

  mycroft_enclosure:
    container_name: mycroft_enclosure
    hostname: mycroft_enclosure
    restart: unless-stopped
    image: smartgic/mycroft-enclosure:${VERSION}
    network_mode: host
    ipc: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
    depends_on:
      - mycroft_bus

  mycroft_cli:
    container_name: mycroft_cli
    hostname: mycroft_cli
    restart: unless-stopped
    image: smartgic/mycroft-cli:${VERSION}
    network_mode: host
    ipc: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
      - mycroft_skills_venv:/opt/mycroft-venv
      - mycroft_skills_repo:/opt/mycroft
      - mycroft_skills:/opt/mycroft/skills
    depends_on:
      - mycroft_bus

  mycroft_audio:
    container_name: mycroft_audio
    hostname: mycroft_audio
    restart: unless-stopped
    image: smartgic/mycroft-audio:${VERSION}
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/mycroft/.config/pulse/cookie
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ~/.config/pulse/cookie:/home/mycroft/.config/pulse/cookie:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - mycroft_skills:/opt/mycroft/skills
    depends_on:
      - mycroft_bus

  mycroft_voice:
    container_name: mycroft_voice
    hostname: mycroft_voice
    restart: unless-stopped
    image: smartgic/mycroft-voice:${VERSION}
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/mycroft/.config/pulse/cookie
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${WEBCACHE_FOLDER}:/home/mycroft/.cache/mycroft
      - ${MODELS_FOLDER}:/home/mycroft/models
      - ${MIMIC3_VOICES_FOLDER}:/home/mycroft/.local/share/mycroft/mimic3/voices
      - ~/.config/pulse/cookie:/home/mycroft/.config/pulse/cookie:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${CACHE_FOLDER}:/tmp/mycroft
    depends_on:
      - mycroft_bus
      - mycroft_audio

  mycroft_skills:
    container_name: mycroft_skills
    hostname: mycroft_skills
    restart: unless-stopped
    image: smartgic/mycroft-skills:${VERSION}
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/mycroft/.config/pulse/cookie
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}:/home/mycroft/.config/mycroft
      - ${WEBCACHE_FOLDER}:/home/mycroft/.cache/mycroft
      - ~/.config/pulse/cookie:/home/mycroft/.config/pulse/cookie:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${CACHE_FOLDER}:/tmp/mycroft
      - mycroft_skills_venv:/opt/mycroft-venv
      - mycroft_skills_repo:/opt/mycroft
      - mycroft_skills:/opt/mycroft/skills
      - /sys:/sys:ro
    depends_on:
      - mycroft_enclosure

  mycroft_gui:
    container_name: mycroft_gui
    restart: unless-stopped
    image: smartgic/mycroft-gui:${VERSION}
    network_mode: host
    ipc: host
    devices:
      - /dev/dri
    environment:
      DISPLAY: :0
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${X11_SOCKET}:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth
      - mycroft_skills:/opt/mycroft/skills
    depends_on:
      - mycroft_enclosure
