FROM smartgic/mycroft-base:armhf-dev

LABEL vendor=Smartgic.io \
      io.smartgic.maintainer="Gaëtan Trellu <gaetan.trellu@smartgic.io>" \
      io.smartgic.image-name="mycroft-bus" \
      io.smartgic.is-beta="no" \
      io.smartgic.is-production="no" \
      io.smartgic.version="dev" \
      io.smartgic.release-date="2021-01-01"

WORKDIR /home/mycroft/core

USER mycroft

EXPOSE 8181

ENTRYPOINT ["python", "-m", "mycroft.messagebus.service"]
